### ISSUE TITLE
How to discovery endpoints of any listening KNXnet/IP server?

### ISSUE THREAD

**Issue by stonedong** [pitschr/knx-core#11]
Can you show the demo code?

**Comment by pitschr** [comment]
Examples can be found here: https://github.com/pitschr/knx-examples
For a more advanced example / Demo Application, I may refer you to: https://github.com/pitschr/knx-demo-tty-monitor

Does it answer your question?

**Comment by stonedong** [comment]
AH no, about the example I tried the read/write API, it works! but I do not found the discovery API.

according the specification, the client send the SEARCH_REQUEST, then will receive SEARCH_RESPONSE, it contains the server endpoints information. do you have realize the function and give the APIs ?

I use KNX virtual to learning.

**Comment by pitschr** [comment]
I am not sure why I do not see your comment here (perhaps you deleted it)?

> AH no, about the example I tried the read/write API, it works! but I do not found the discovery API.
> 
> according the specification, the client send the SEARCH_REQUEST, then will receive SEARCH_RESPONSE, it contains the server endpoints information. do you have realize the function and give the APIs ?
> 
> I use KNX virtual to learning.

To answer your question:

The knx-core is designed that you don't worry about the KNX internal mechanism/logic like discovery, as it will do the hard job for you. As you are more interested in KNX internal topics like discovery, perhaps it is better when you check out the Calimero project. An example can be found here how to do it:
https://github.com/calimero-project/introduction/blob/master/src/main/java/DiscoverKnxServers.java

When speaking about my project (knx-core), then KNX internal stuffs like discovery are handled internally, there is no public API available. But for your interest you can take a look how it is done internally:
https://github.com/pitschr/knx-core/blob/main/src/main/java/li/pitschmann/knx/core/communication/InternalKnxClient.java#L515

The discovery logic is chosen by the knx-core automatically, as soon no specific IP address (wildcard / unbound) has been provided. If you provide a specific IP address of your KNX router/interface, then discovery mechanism is skipped as there is no need to for knx-core to search/discover for the most suitable KNX router/interface.

Using knx-core just use: `DefaultKnxClient.createStarted();` and it will do the discovery for you and connect to the first KNX router/interface that responded.

In nutshell, feel free to check out how I implemented it, but there is no public API / method available for you. The knx-core project is designed for developers who are interested to send KNX commands like "switch on the lamp" rather than about KNX internal mechanism like discovery, hardware description, connect, disconnect and health-check as knx-core is handling it for you.

**Comment by stonedong** [comment]
If in the same network, there are four KNXnet/IP servers. Using "DefaultKnxClient.createStarted();" will return one of them. Is it right?

If I do not know the servers's IPs, I just can operate one of them?

**Comment by pitschr** [comment]
Yes. If there are four KNXnet/IP services in your network, then the fastest one that responded will be chosen by the knx-core (other three responses are ignored then).

The workflow is basically:
1) knx-core sends a search request like "Hey! Are there some KNXnet/IP devices in this network?"
2) All KNXnet/IP devices in the same network will answer "Yes, I am there" and each of them will provide their own IP address in the response packet
3) knx-core will fetch all "search responses", but only the first response is considered
4) knx-core establish the connection to the KNXnet/IP device that repsonded first

Discovery service is fine and safe when you have only one KNXnet/IP device in your network, in this case you don't have to worry that knx-core might select a KNXnet/IP device in behalf of you. If you want to have a control, which KNXnet/IP device shall be used by knx-core, then provide the IP address.

For example, if your your KNXnet/IP device has the ip address `192.168.0.3`, then you can tell KNX client to skip the discovery service and connect directly using  `DefaultKnxClient.createStarted("192.168.0.3");`

**Comment by stonedong** [comment]
I have one more question. Can I scan to get the node points data in KNXnet/IP device?

For example, there is a KNXnet/IP device, the device has four function node points, can I scan to get the groupAddress of them?

I am not sure my question description clear!

**Comment by pitschr** [comment]
Information like Group Addresses and Data Point Types are not part of the KNXnet/IP packets. So you cannot get group addresses from KNX devices itself. Only when you have a valid group address / data point type, the KNX device will react on it. The group addresses and data point types are defined and described by the ETS tool which creates a KNXPROJ file. knx-core supports KNXPROJ file to obtain the group addresses, based on this KNXPROJ file the data may be auto-translated to / from KNX devices.

I am not aware of bacnet, the knx-core is implemented based on KNX specification and it doesn't offer functionality outside of the KNX specification.

Does it answer your question?

**Comment by stonedong** [comment]
en, nice you!
