### ISSUE TITLE
Stopped working with v0.4

### ISSUE THREAD

**Issue by StefanOltmann** [pitschr/knx-core#14]
Hi Christoph,

I updated from knx-core v0.3 to the current knx-core v0.5 and noticed that it does not work anymore on my site.
This is also the case with knx-core v0.4.

With v0.3 and otherwise same codebase it still works.

**knx-core v0.3:** [working-server.log](https://github.com/pitschr/knx-core/files/6537668/working-server.log) & [working-knx-audit.log](https://github.com/pitschr/knx-core/files/6537667/working-knx-audit.log)
**knx-core v0.4:** [broken-server.log](https://github.com/pitschr/knx-core/files/6537666/broken-server.log) & [broken-knx-audit.log](https://github.com/pitschr/knx-core/files/6537665/broken-knx-audit.log)

Kind regards,

Stefan

**Comment by pitschr** [comment]
Hi Stefan.

I'm sorry to hear it. However, I need your help to reproduce the issue, since it is working on my side and CI/CD pipeline also confirm that there are no broken changes. Given KNX Audit I see that the acknowledge packets were really not arrived for some requests.

I compared 0.3 with 0.4 and following might be breaking changes:
* Changing readRequest() and writeRequest() to asynchronous: https://github.com/pitschr/knx-core/commit/664f556b8e0c860ee7bb50247cf66606d0a642a0#diff-99db71d5718b9f7c9131b9f5e8fdbc61d6686f8331a2b64349de2e6fde3fbefe

* Dropping `li.pitschmann.knx.core.utils.Executors` to use the `java.util.concurrent.Executors` (not necessary anymore, because I took it for MDC to spot the concurrency issues during e.g. load testing): https://github.com/pitschr/knx-core/commit/0bea71d775fe5edd34f4401ebb1750ef349d55b2

I doubt that it is because of the Executors. For some reasons you are sending too much packets in short time the packets may be dropped by your KNX Net/IP device as KNX TP cannot handle much traffic. I do not have a rate limit implemented, therefore I would like to ask if you face the same issue when you make the read/write request methods blocking again. In this case the KNX Client will proceed with next packet only when the ACK packet arrived. As per UDP communication, the packets may be dropped, and according to KNX Specification the requests are sent up to 3 times only. When looking at your `broken-server.log` then I see, that it tried request nr 31 three times (0 ack) and failed. The request 25 was sent twice times (1 ack) and succeeded.

The blocking operations have been re-added in KNX Core 0.5.0 while the method signature has been changed by adding a timeout value: https://github.com/pitschr/knx-core/commit/92d79b52e7f88eb2b961da5afac08ac92f6d1c27

My proposal for next step would be:
1. Change version of knx-core (and knx-plugins) back to 0.5.0
1. Change your code
```
knxClient.readRequest(GroupAddress.of(groupAddress))
```
to
```
knxClient.readRequest(GroupAddress.of(groupAddress), 3000L);
```

This is the blocking operation you used like in 0.3.0. Can you check if that solves your issue? If yes, then the rate limit has to be implemented when you want to perform with non-blocking operation. According to KNX specification the rate limit is required for Routing only, not for Tunneling. The KNX Client itself is able to handle thousands packets without issue.

Let me know if changing from non-blocking to blocking method resolves the issue.

**Comment by StefanOltmann** [comment]
> 2. Change your code
> 
> ```
> knxClient.readRequest(GroupAddress.of(groupAddress))
> ```
> 
> to
> 
> ```
> knxClient.readRequest(GroupAddress.of(groupAddress), 3000L);
> ```
> 
> This is the blocking operation you used like in 0.3.0. Can you check if that solves your issue? If yes, then the rate limit has to be implemented when you want to perform with non-blocking operation. According to KNX specification the rate limit is required for Routing only, not for Tunneling. The KNX Client itself is able to handle thousands packets without issue.
> 
> Let me know if changing from non-blocking to blocking method resolves the issue.

Yes, that solves the issue. Thank you!

> For some reasons you are sending too much packets in short time

Indeed. Intentional. At startup of my service I request the current state of every known device and from that point in time on I watch changes using the group monitor. So my clients can refresh the current device states from my service without causing any new requests this way.

See https://github.com/StefanOltmann/smart-home-server/blob/06d17dbcdc7e58f6d45a04c68ecdd55f475aa123/src/main/kotlin/de/stefan_oltmann/smarthome/server/knx/KnxServiceImpl.kt#L99-L128

This takes only a second for all my devices and only once at startup. I can live with that. ;)

It's interesting that this initial READ REQUEST "spam" breaks something in a way that WRITE REQUESTs many seconds later don't work.

We can consider this issue resolved.

Or do you want to take any measures to prevent using the client wrongly in the way I did?

**Comment by pitschr** [comment]
No need to measure more. I am glad that my guess was correct. My release note for 0.4.0 was most probably not clear enough about the move from blocking to non-blocking as default one.

It is working as per specification (UDP allows dropping packets, that is why we resend request packets up to 3 times). This number is hardcoded with https://github.com/pitschr/knx-core/blob/main/src/main/java/li/pitschmann/knx/core/config/CoreConfigs.java#L312 . If you think it would make sense to make the number configurable, then I can consider it. Or increase the timeout for tunneling request using `client.communication.tunneling.requestTimeout` https://github.com/pitschr/knx-core/blob/main/src/main/java/li/pitschmann/knx/core/config/CoreConfigs.java#L266

In this case the KNX Client is more forgiving than in KNX Specification as it floods the KNX Net/IP device.

----

Another (weak) option would be using non-blocking operatoin but give some delay to allow KNX Net/IP device to breath. Although the proper implementation of rate limit is the very best solution maybe but here I'm afraid that I may open a jar of other issues (e.g. number of threads in Executor may be limited which may cause a side effect).

For now I consider the case as resolved as your approach was too extreme. If you think we should improve it, feel free to reopen or raise new request.

Happy coding!
